services:
  db:
    ports:
      - "5432:5432"  # connect with psql/DBeaver if you want

  api:
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_DEBUG: 1
      DJANGO_ALLOWED_HOSTS: "*"
      CSRF_TRUSTED_ORIGINS: "http://localhost"
    volumes:
      - ./api/src:/app
    ports:
      - "8000:8000"

  web:
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:8000
    command: npm run dev
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  proxy:
    ports:
      - "80:80"
    environment:
      DOMAIN: localhost

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on: [db]
    networks: [app]

