# Generated by Django 5.2.5 on 2025-12-12 00:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="asset_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Full value of the asset (100% ownership).",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="listing",
            name="seller_retain_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Percentage of the asset the seller keeps (0–100).",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
